# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "BirdBath"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"

  config.vm.network :forwarded_port, guest: 3000, host: 13000
  config.vm.network :forwarded_port, guest: 27017, host: 37017

  config.ssh.forward_agent = true
  
  config.vm.synced_folder "../", "/home/vagrant/BirdBath"
 
  config.vm.provider :virtualbox do |vb|
     vb.customize ["modifyvm", :id, "--memory", "1024"]
  end
  
  config.vm.provision :shell, :path => "bootstrap.sh"
end
